on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run tsc
      - run: node dist/server.js